#!/bin/python3

import sys

def timeCompare(t1, t2):
    # Complete this function
    l=list(t1)
    l1=list(t2)
    i=p=0
    if l[-2] > l1[-2]:
        print('Second')
    elif l[-2] < l1[-2]:
        print('First')
    else:
        while i<5:
            if l[i]!=l1[i] and p<1:
                if l[i]>l1[i]:
                    print('Second')
                    p+=1
                    i+=1
                else:
                    print('First')
                    p+=1
                    i+=1

            else:
                i+=1


q = int(input().strip())
for a0 in range(q):
    t1, t2 = input().strip().split(' ')
    t1, t2 = [str(t1), str(t2)]
    result = timeCompare(t1, t2)
    #print(result.lstrip())